name: Rapport quotidien Equilibre

on:
  schedule:
    # , tous les jours 
    - cron: '0 5 * * *'
    - cron: '0 11 * * *'   # 12h00
    - cron: '0 18 * * *'   # 19h00
    - cron: '0 21 * * *'   # 21h00
    
  workflow_dispatch:   # permet aussi de le lancer à la main

jobs:
  rapport:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Envoyer le rapport sur Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GOATCOUNTER_TOKEN: ${{ secrets.GOATCOUNTER_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
        run: python .github/scripts/rapport.py
